plugins {
    id 'java-library'
    id 'maven-publish'
    id 'eclipse'
    id 'com.gtnewhorizons.retrofuturagradle' version '2.0.2'
}

group = 'net.ilexiconn'
version = getLLibraryVersion() + '-1.7.10'

base {
    archivesName = 'llibrary'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
    withSourcesJar()
    withJavadocJar()
}

minecraft {
    mcVersion.set('1.7.10')
    username.set('Developer')
}

repositories {
    mavenCentral()
    maven {
        name = 'GTNH Maven'
        url = uri('https://nexus.gtnewhorizons.com/repository/public/')
    }
}

tasks.named('processResources') {
    def projVersion = project.version.toString()
    def mcVersion = minecraft.mcVersion.get()

    inputs.property 'version', projVersion
    inputs.property 'mcversion', mcVersion

    filesMatching('mcmod.info') {
        expand 'version': projVersion, 'mcversion': mcVersion
    }
}

tasks.named('deobfuscateMergedJarToSrg') {
    accessTransformerFiles.from('src/main/resources/META-INF/llibrary_at.cfg')
}

tasks.named('jar') {
    manifest {
        attributes(
            'FMLAT': 'llibrary_at.cfg',
            'FMLCorePlugin': 'net.ilexiconn.llibrary.server.core.plugin.LLibraryPlugin',
            'FMLCorePluginContainsFMLMod': 'true'
        )
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = 'localBuildRepo'
            url = layout.buildDirectory.dir('repo')
        }
    }
}

String getLLibraryVersion() {
    def major = '0'
    def revision = '0'
    def patch = '0'
    def prefix = 'public static final String VERSION = "'
    def versionFile = file('src/main/java/net/ilexiconn/llibrary/LLibrary.java')

    versionFile.eachLine { String line ->
        line = line.trim()
        if (line.startsWith(prefix)) {
            line = line.substring(prefix.length(), line.length() - 2)
            def pts = line.split('\\.')
            major = pts[0]
            revision = pts[1]
            patch = pts[2]
        }
    }

    return "$major.$revision.$patch"
}
